/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empmgmt.gui;

import empmgmt.dbutuil.DBConnection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class OptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form OptionsFrame
     */
    public OptionsFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JrbAddEmp = new javax.swing.JRadioButton();
        jrbSearchEmp = new javax.swing.JRadioButton();
        jrbShowEmp = new javax.swing.JRadioButton();
        jrbQuit = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        jrbUpdateEmployee = new javax.swing.JRadioButton();
        jrbDeleteEmp = new javax.swing.JRadioButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Select Your Choice");

        buttonGroup1.add(JrbAddEmp);
        JrbAddEmp.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        JrbAddEmp.setForeground(new java.awt.Color(255, 255, 255));
        JrbAddEmp.setText("Add Employee");
        JrbAddEmp.setOpaque(false);
        JrbAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbAddEmpActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbSearchEmp);
        jrbSearchEmp.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jrbSearchEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrbSearchEmp.setText("Search Employee");
        jrbSearchEmp.setOpaque(false);

        buttonGroup1.add(jrbShowEmp);
        jrbShowEmp.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jrbShowEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrbShowEmp.setText("Show All Employee");
        jrbShowEmp.setOpaque(false);
        jrbShowEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbShowEmpActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbQuit);
        jrbQuit.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jrbQuit.setForeground(new java.awt.Color(255, 255, 255));
        jrbQuit.setText("Quit");
        jrbQuit.setOpaque(false);
        jrbQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbQuitActionPerformed(evt);
            }
        });

        btnDoTask.setBackground(new java.awt.Color(0, 0, 0));
        btnDoTask.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 255, 255));
        btnDoTask.setText("DO TASK");
        btnDoTask.setOpaque(false);
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        jrbUpdateEmployee.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jrbUpdateEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jrbUpdateEmployee.setText("Update Employee");
        jrbUpdateEmployee.setOpaque(false);
        jrbUpdateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbUpdateEmployeeActionPerformed(evt);
            }
        });

        jrbDeleteEmp.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jrbDeleteEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrbDeleteEmp.setText("Delete Employee");
        jrbDeleteEmp.setOpaque(false);
        jrbDeleteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDeleteEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jrbSearchEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JrbAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbShowEmp)
                            .addComponent(jrbQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbUpdateEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrbDeleteEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnDoTask, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(JrbAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jrbSearchEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jrbShowEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jrbUpdateEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jrbDeleteEmp)
                .addGap(28, 28, 28)
                .addComponent(jrbQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnDoTask, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbQuitActionPerformed
       
    }//GEN-LAST:event_jrbQuitActionPerformed

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
         JFrame UserChoiceFrame=null;
        if(validateInput()==false)
        {
            JOptionPane.showMessageDialog(null,"Please select a Button First!","Deselected!!",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        else if(JrbAddEmp.isSelected()==true)
        {
            UserChoiceFrame=new AddEmployeeFrame();
        }
        else if(jrbSearchEmp.isSelected()==true)
        {
            UserChoiceFrame=new SearchEmployeeFrame();
        }
        else if(jrbShowEmp.isSelected()==true)
        {
           UserChoiceFrame=new ViewAllEmployeeFrame();
        }
        else if(jrbUpdateEmployee.isSelected()==true)
        {
            UserChoiceFrame=new  UpdateEmployee();
        }
        /*else if(jrbDeleteEmp.isSelected()==true)
        {
           UserChoiceFrame=new DeleteEmployeeFrame();
        }*/
        else
        {   
        // JOptionPane.showInputDialog(null,"What is Your name?","Name Required?",JOptionPane.QUESTION_MESSAGE);  
         JOptionPane.showMessageDialog(null,"Thankyou for Using the App!","Thanks!!",JOptionPane.INFORMATION_MESSAGE);  
         DBConnection.closeConnection();
         System.exit(0);
        }
        UserChoiceFrame.setVisible(true);
        dispose();
            
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void jrbUpdateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbUpdateEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbUpdateEmployeeActionPerformed

    private void JrbAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbAddEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JrbAddEmpActionPerformed

    private void jrbShowEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbShowEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbShowEmpActionPerformed

    private void jrbDeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDeleteEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbDeleteEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JrbAddEmp;
    private javax.swing.JButton btnDoTask;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbDeleteEmp;
    private javax.swing.JRadioButton jrbQuit;
    private javax.swing.JRadioButton jrbSearchEmp;
    private javax.swing.JRadioButton jrbShowEmp;
    private javax.swing.JRadioButton jrbUpdateEmployee;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
     return !(JrbAddEmp.isSelected()==false&&jrbSearchEmp.isSelected()==false&&jrbShowEmp.isSelected()==false&&jrbQuit.isSelected()==false&&jrbUpdateEmployee.isSelected()==false);   
    //  && jrbDeleteEmp.isSelected()==false
    }
}
